
defaults:
  - dataset: mura_224
  - vision_model: vit_b16_224_dr_bert
  - eval_type: linear
  - _self_

seed: 12345
batch_size: 64
num_workers: 16
max_epochs: 1000
precision: 16-mixed
accelerator: gpu

classifier_dropout: 0.5
pool_image: True
learning_rate: 1e-4
weight_decay: 1e-6
freeze_encoder: ${eval_type.freeze_encoder}

project_name: vlp_classification_benchmark
experiment_name: ${hydra:runtime.choices.vision_model}-${hydra:runtime.choices.eval_type}
