
defaults:
  - dataset: grazpedwri
  - detection_model: vit_b16_224_dr_bert
  - eval_type: fine_tuning_all
  - _self_

seed: 12345
batch_size: 16
accumulate_grad_batches: 16
num_workers: 16
max_epochs: 1000
precision: 16-mixed
accelerator: gpu

detector_learning_rate: 1e-5
encoder_learning_rate: 1e-7
weight_decay: 1e-6
freeze_encoder: ${eval_type.freeze_encoder}

project_name: vlp_detection_benchmark
experiment_name: ${hydra:runtime.choices.detection_model}-${hydra:runtime.choices.eval_type}
