
defaults:
  - dataset: rsna_bone_age_224
  - vision_model: vit_b16_224_dr_bert
  - eval_type: linear_all
  - _self_

seed: 12345
batch_size: 64
accumulate_grad_batches: 1
num_workers: 16
max_epochs: 1000
precision: 16-mixed
accelerator: gpu

head_dropout: 0.2
head_learning_rate: 1e-3
encoder_learning_rate: 1e-6
weight_decay: 1e-6
freeze_encoder: ${eval_type.freeze_encoder}

project_name: vlp_regression_benchmark
experiment_name: ${hydra:runtime.choices.vision_model}-${hydra:runtime.choices.eval_type}-${hydra:runtime.choices.dataset}
