_target_: datasets.grazpedwri.ClassificationGRAZPEDWRIDataModule
_args_:
  - "GRAZPEDWRI-DX"
  - ${batch_size}
num_workers: ${num_workers}
train_ratio: ${eval_type.train_ratio}
train_transform:
  _target_: albumentations.Compose
  _args_:
    - - _target_: albumentations.LongestMaxSize
        max_size: 224
      - _target_: albumentations.PadIfNeeded
        min_height: 224
        min_width: 224
        border_mode: 0
      - _target_: albumentations.Normalize
        mean:
          - 0.5
          - 0.5
          - 0.5
        std:
          - 0.25
          - 0.25
          - 0.25
        p: 1
      - _target_: albumentations.pytorch.transforms.ToTensorV2

test_transform:
  _target_: albumentations.Compose
  _args_:
    - - _target_: albumentations.LongestMaxSize
        max_size: 224
      - _target_: albumentations.PadIfNeeded
        min_height: 224
        min_width: 224
        border_mode: 0
      - _target_: albumentations.Normalize
        mean:
          - 0.5
          - 0.5
          - 0.5
        std:
          - 0.25
          - 0.25
          - 0.25
        p: 1
      - _target_: albumentations.pytorch.transforms.ToTensorV2
