_target_: datasets.grazpedwri.GRAZPEDWRIDataModule
_args_:
  - "GRAZPEDWRI-DX"
num_workers: ${num_workers}
batch_size: ${batch_size}
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  _args_: ${detection_model._args_.0.text_model._args_}
classname_list:
  - "anomalie osseuse"
  - "lésion osseuse"
  - "corps étranger"
  - "fracture"
  - "matériel implanté"
  - "aposition périostée"
  - "signe du carré pronateur"
  - "gonflement des parties molles"
  - "text"
train_transform:
  _target_: albumentations.Compose
  _args_:
    - - _target_: albumentations.LongestMaxSize
        max_size: 224
      - _target_: albumentations.PadIfNeeded
        min_height: 224
        min_width: 224
        border_mode: 0
      - _target_: albumentations.Normalize
        mean:
          - 0.5
          - 0.5
          - 0.5
        std:
          - 0.25
          - 0.25
          - 0.25
        p: 1
      - _target_: albumentations.pytorch.transforms.ToTensorV2
  bbox_params:
    _target_: albumentations.BboxParams
    format: yolo
    label_fields:
      - "class_labels"
test_transform:
  _target_: albumentations.Compose
  _args_:
    - - _target_: albumentations.LongestMaxSize
        max_size: 224
      - _target_: albumentations.PadIfNeeded
        min_height: 224
        min_width: 224
        border_mode: 0
      - _target_: albumentations.Normalize
        mean:
          - 0.5
          - 0.5
          - 0.5
        std:
          - 0.25
          - 0.25
          - 0.25
        p: 1
      - _target_: albumentations.pytorch.transforms.ToTensorV2
  bbox_params:
    _target_: albumentations.BboxParams
    format: yolo
    label_fields:
      - "class_labels"