_target_: datasets.mura.MURADataModule
_args_:
  - "MURA"
  - ${batch_size}
num_workers: ${num_workers}
study_level: false
train_ratio: ${eval_type.train_ratio}
train_transform:
  _target_: albumentations.Compose
  _args_:
    - - _target_: albumentations.Resize
        height: 224
        width: 224
      - _target_: albumentations.Normalize
        mean:
          - 0.5
          - 0.5
          - 0.5
        std:
          - 0.25
          - 0.25
          - 0.25
        p: 1
      - _target_: albumentations.pytorch.transforms.ToTensorV2

test_transform:
  _target_: albumentations.Compose
  _args_:
    - - _target_: albumentations.Resize
        height: 224
        width: 224
      - _target_: albumentations.Normalize
        mean:
          - 0.5
          - 0.5
          - 0.5
        std:
          - 0.25
          - 0.25
          - 0.25
        p: 1
      - _target_: albumentations.pytorch.transforms.ToTensorV2
