_target_: datasets.rsna_bone_age.RSNABoneAgeDataModule
_args_:
  - "rsna_bone_age"
batch_size: ${batch_size}
num_workers: ${num_workers}
train_ratio: ${eval_type.train_ratio}
train_transform:
  _target_: albumentations.Compose
  _args_:
    - - _target_: albumentations.Resize
        height: 336
        width: 336
      - _target_: albumentations.Normalize
        mean:
          - 0.5
          - 0.5
          - 0.5
        std:
          - 0.25
          - 0.25
          - 0.25
        p: 1
      - _target_: albumentations.pytorch.transforms.ToTensorV2

test_transform:
  _target_: albumentations.Compose
  _args_:
    - - _target_: albumentations.Resize
        height: 336
        width: 336
      - _target_: albumentations.Normalize
        mean:
          - 0.5
          - 0.5
          - 0.5
        std:
          - 0.25
          - 0.25
          - 0.25
        p: 1
      - _target_: albumentations.pytorch.transforms.ToTensorV2
