_target_: models.modeling_vitxrs.ViTXRSModel.from_pretrained
_args_:
  - "./checkpoints/vit_b16_224-sapbert_xlmr/vision_encoder"
config:
  _target_: models.modeling_vitxrs.ViTXRSConfig.from_pretrained
  _args_:
    - "./checkpoints/vit_b16_224-sapbert_xlmr/vision_encoder"
  seq_model: false